# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='my_album',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='my_photo',
        ),
    ]
